filetype on          
syntax on            
set background=dark  
set linebreak        
set visualbell       
set showmatch        
set hlsearch         
set autoindent       
set expandtab        
set shiftwidth=2     
set smartindent      
set smarttab         
set softtabstop=2    
set mouse=a          