[cargo-new]
name = "F9mc"
vcs = "git"

[alias]     
b = "build"
c = "check"
t = "test"
r = "run"
rr = "run --release"
recursive_example = "rr --example recursions"
space_example = ["run", "--release", "--", "\"command list\""]
ins = "install --force --path ."

[build]
jobs = 1                      
rustc = "rustc"               
rustdoc = "rustdoc"           
target = "triple"             
target-dir = "target"            
incremental = true                   

[doc]
browser = "chromium"                               

[env]
RUST_LOG = "info"

[future-incompat-report]
frequency = 'always'                      

[install]
root = "/some/path"    #TODO     

[term]
quiet = false          
verbose = false        
color = 'auto' 
